# Generated by Django 5.2.4 on 2025-08-09 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.FileField(blank=True, upload_to="photos/"),
        ),
    ]
