# Generated by Django 5.2.4 on 2025-08-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plans", "0002_plan_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
