# Generated by Django 5.2.4 on 2025-07-26 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="publis_date",
            new_name="publish_date",
        ),
        migrations.AddField(
            model_name="category",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribed_categories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
